version: "3.1"

services:
  server:
    build: ./back
    restart: always
    ports:
      - 4000:4000
    volumes:
     - ./back/src:/back/src  
  
  client:
    build: ./front
    ports:
      - 3000:3000
    volumes:
     - ./front/src:/app/src
   
  db:
    image: postgres
    volumes: 
      - ./data:/var/lib/postgresql/data

    restart: always
    ports:
      - 5432:5432
    container_name: ke4_db
    environment:
      POSTGRES_PASSWORD: ke4db
      POSTGRES_USER: ke4user
      POSTGRES_DB: ke4
    
      