version: '3'


services:

  server:

    # build: ./server

    # To replace with the correct path of your server image

    image: tdashh/2109-wns-remote2-ke4_server

    command: sh -c "npm run build && npm run start"

    ports:
      - 4000:4000
    volumes:
     - ./back/src:/back/src

    depends_on:

      - postgres

  client:

    # build: ./client

    # To replace with the correct path of your client image

    image: tdashh/2109-wns-remote2-ke4_client
    ports:
      - 3000:3000
    command: sh -c "npm run build"

    volumes:

      - web-client-build:/app/build  

  postgres:

    image: postgres

  nginx:

    image: nginx:1.21.3

    depends_on:

      - server

      - client

    restart: always

    ports:

      - ${GATEWAY_PORT}:80

    volumes:

      - ./nginx.conf:/etc/nginx/nginx.conf

      - web-client-build:/web-client-build

      - ./logs:/var/log/nginx