services:
  server:
    build: ./back
    ports:
      - 5050:5000
    command: npm run dev
    volumes:
      - ./server/src/:/app/src
  client:
    build: ./front
    ports:
      - 8080:3000
    command: npm run start
