version: "3.1"

services:
  server:
    build: ./back
    restart: always
    ports:
      - 5050:5000
  
  client:
    build: ./front
    ports:
      - 8080:3000
   
  db:
    image: postgres
    volumes: 
      - ./data:/var/lib/postgresql/data

    restart: always
    ports:
      - 5438:5432
    container_name: ke4_db
    environment:
      POSTGRES_PASSWORD: ke4db
      POSTGRES_USER: ke4user
      POSTGRES_DB: ke4
    
      