version: "3.1"

services:
  server:
    build: ./back
    restart: always
    ports:
      - 4000:4000
    volumes:
     - ./back/src:/back/src  

  client:
    build: ./front
    ports:
      - 3000:3000
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build

  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

    environment:
      POSTGRES_PASSWORD: ke4db
      POSTGRES_USER: ke4user
      POSTGRES_DB: ke4

  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT:-8000}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
      - ./logs:/var/log/nginx  

volumes:
  web-client-build:         
     
